// src/constants/exercises.js
export const EXERCISE_COMPENDIUM = [
  // Cardio
  { cat:"Cardio", name:"Walking, slow (2 mph)",             met:2.5  },
  { cat:"Cardio", name:"Walking, moderate (3 mph)",         met:3.5  },
  { cat:"Cardio", name:"Walking, brisk (3.5 mph)",          met:4.3  },
  { cat:"Cardio", name:"Walking, fast (4 mph)",             met:5.0  },
  { cat:"Cardio", name:"Jogging, light (5 mph)",            met:7.0  },
  { cat:"Cardio", name:"Running, moderate (6 mph)",         met:9.8  },
  { cat:"Cardio", name:"Running, fast (7.5 mph)",           met:12.3 },
  { cat:"Cardio", name:"Running, very fast (10 mph)",       met:16.0 },
  { cat:"Cardio", name:"Cycling, leisure (<10 mph)",        met:4.0  },
  { cat:"Cardio", name:"Cycling, moderate (12-14 mph)",     met:8.0  },
  { cat:"Cardio", name:"Cycling, vigorous (16-19 mph)",     met:12.0 },
  { cat:"Cardio", name:"Cycling, stationary, moderate",     met:6.8  },
  { cat:"Cardio", name:"Cycling, stationary, vigorous",     met:8.8  },
  { cat:"Cardio", name:"Elliptical trainer, moderate",      met:5.0  },
  { cat:"Cardio", name:"Elliptical trainer, vigorous",      met:8.5  },
  { cat:"Cardio", name:"Rowing machine, moderate",          met:7.0  },
  { cat:"Cardio", name:"Rowing machine, vigorous",          met:8.5  },
  { cat:"Cardio", name:"Jump rope, moderate",               met:10.0 },
  { cat:"Cardio", name:"Jump rope, fast",                   met:12.3 },
  { cat:"Cardio", name:"Stair climbing machine",            met:9.0  },
  { cat:"Cardio", name:"Hiking, moderate terrain",          met:5.3  },
  { cat:"Cardio", name:"Hiking, steep terrain",             met:7.8  },
  // Strength & HIIT
  { cat:"Strength", name:"Weight training, light effort",   met:3.0  },
  { cat:"Strength", name:"Weight training, vigorous",       met:6.0  },
  { cat:"Strength", name:"Bodyweight exercises (general)",  met:3.8  },
  { cat:"Strength", name:"Circuit training (minimal rest)", met:8.0  },
  { cat:"Strength", name:"HIIT, general",                   met:8.0  },
  { cat:"Strength", name:"HIIT, vigorous",                  met:10.3 },
  { cat:"Strength", name:"Kettlebell training",             met:8.2  },
  { cat:"Strength", name:"Calisthenics, light",             met:3.5  },
  { cat:"Strength", name:"Calisthenics, vigorous",          met:8.0  },
  { cat:"Strength", name:"CrossFit / functional training",  met:9.0  },
  // Flexibility & Mind-Body
  { cat:"Flexibility", name:"Yoga, Hatha",                  met:2.5  },
  { cat:"Flexibility", name:"Yoga, Power/Vinyasa",          met:4.0  },
  { cat:"Flexibility", name:"Pilates, general",             met:3.0  },
  { cat:"Flexibility", name:"Stretching, light",            met:2.3  },
  { cat:"Flexibility", name:"Tai Chi",                      met:3.0  },
  // Swimming & Water
  { cat:"Swimming", name:"Swimming, leisurely",             met:6.0  },
  { cat:"Swimming", name:"Swimming, moderate laps",         met:7.0  },
  { cat:"Swimming", name:"Swimming, vigorous laps",         met:9.8  },
  { cat:"Swimming", name:"Water aerobics",                  met:5.5  },
  // Sports
  { cat:"Sports", name:"Football / soccer, recreational",   met:7.0  },
  { cat:"Sports", name:"Football / soccer, competitive",    met:10.0 },
  { cat:"Sports", name:"Basketball, game",                  met:8.0  },
  { cat:"Sports", name:"Tennis, singles",                   met:8.0  },
  { cat:"Sports", name:"Tennis, doubles",                   met:6.0  },
  { cat:"Sports", name:"Badminton, recreational",           met:5.5  },
  { cat:"Sports", name:"Cricket, batting/fielding",         met:5.0  },
  { cat:"Sports", name:"Golf, carrying clubs",              met:5.3  },
  { cat:"Sports", name:"Squash",                            met:12.0 },
  { cat:"Sports", name:"Table tennis / ping pong",          met:4.0  },
  { cat:"Sports", name:"Volleyball, recreational",          met:3.0  },
  { cat:"Sports", name:"Dancing, aerobic/general",          met:6.5  },
  { cat:"Sports", name:"Dancing, ballroom, slow",           met:3.0  },
  // Daily activity
  { cat:"Daily", name:"Gardening, general",                 met:3.5  },
  { cat:"Daily", name:"House cleaning, vigorous",           met:3.5  },
  { cat:"Daily", name:"Carrying heavy loads",               met:7.5  },
];
