// scripts/quality-report.mjs — Fix 24 code-quality report (worst offenders first)
// Runs ESLint, keeps only the code-quality warnings (eslint.config.js QUALITY)
// and prints a Markdown report. Usage: npm run quality [> report.md]
import { ESLint } from "eslint";
import { QUALITY } from "../eslint.config.js";

const RULES = Object.keys(QUALITY);
const limit = (r) => {
  const o = QUALITY[r][1];
  return typeof o === "object" ? o.max : o;
};
const results = await new ESLint().lintFiles(["."]);
const rows = [];
for (const f of results) {
  const file = f.filePath
    .replace(process.cwd() + "/", "")
    .replace(/\\/g, "/")
    .replace(process.cwd().replace(/\\/g, "/") + "/", "");
  for (const m of f.messages) {
    if (!RULES.includes(m.ruleId)) continue;
    const value =
      Number(
        (m.message.match(/\((\d+)\)/) ||
          m.message.match(/has (\d+) statements/) ||
          m.message.match(/of (\d+)/) ||
          [])[1],
      ) || null;
    const name =
      (m.message.match(
        /^(?:Arrow function|Function|Method|Async function|Async arrow function)?\s*'?([\w$]+)'?/,
      ) || [])[1] || "";
    rows.push({
      rule: m.ruleId,
      file,
      line: m.line,
      value,
      limit: limit(m.ruleId),
      name: /^(has|too|complexity|This|File|Blocks)$/.test(name) ? "" : name,
      msg: m.message,
    });
  }
}
const by = (r) => rows.filter((x) => x.rule === r).sort((a, b) => (b.value ?? 0) - (a.value ?? 0));
const today = new Date().toISOString().slice(0, 10);
let out = `# Code quality report — ${today}\n\nGenerated by \`npm run quality\` (ESLint, rules in \`eslint.config.js\` → \`QUALITY\`). Warnings only — nothing is blocked yet.\n\n`;
out += `| Standard | Limit | Breaches |\n|---|---|---|\n`;
for (const r of RULES) out += `| \`${r}\` | ${limit(r)} | ${by(r).length} |\n`;
for (const r of RULES) {
  const list = by(r);
  if (!list.length) continue;
  out += `\n## ${r} (limit ${limit(r)})\n\n| Value | Where | Function |\n|---|---|---|\n`;
  for (const x of list)
    out += `| ${x.value ?? "—"} | \`${x.file}:${x.line}\` | ${x.name || "—"} |\n`;
}
const perFile = {};
for (const x of rows) perFile[x.file] = (perFile[x.file] || 0) + 1;
out += `\n## Breaches per file\n\n| File | Breaches |\n|---|---|\n`;
for (const [f, n] of Object.entries(perFile).sort((a, b) => b[1] - a[1]))
  out += `| \`${f}\` | ${n} |\n`;
console.log(out);
