// scripts/quality-report.mjs — Fix 24 code-quality report (worst offenders first)
// Runs ESLint, keeps only the code-quality warnings (eslint.config.js QUALITY)
// and prints a Markdown report. Usage: npm run quality [> report.md]
import { ESLint } from "eslint";
import { QUALITY, TARGETS, TARGET_LENGTH, CLEAN_FILES } from "../eslint.config.js";

const RULES = Object.keys(QUALITY);
const limit = (r) => {
  const o = QUALITY[r][1];
  return typeof o === "object" ? o.max : o;
};
const results = await new ESLint().lintFiles(["."]);
const rows = [];
for (const f of results) {
  const file = f.filePath
    .replace(process.cwd() + "/", "")
    .replace(/\\/g, "/")
    .replace(process.cwd().replace(/\\/g, "/") + "/", "");
  for (const m of f.messages) {
    if (!RULES.includes(m.ruleId)) continue;
    const value =
      Number(
        (m.message.match(/\((\d+)\)/) ||
          m.message.match(/has (\d+) statements/) ||
          m.message.match(/of (\d+)/) ||
          [])[1],
      ) || null;
    const name =
      (m.message.match(
        /^(?:Arrow function|Function|Method|Async function|Async arrow function)?\s*'?([\w$]+)'?/,
      ) || [])[1] || "";
    rows.push({
      rule: m.ruleId,
      file,
      line: m.line,
      value,
      limit: limit(m.ruleId),
      name: /^(has|too|complexity|This|File|Blocks)$/.test(name) ? "" : name,
      msg: m.message,
    });
  }
}
const by = (r) => rows.filter((x) => x.rule === r).sort((a, b) => (b.value ?? 0) - (a.value ?? 0));
const today = new Date().toISOString().slice(0, 10);
let out = `# Code quality report — ${today}\n\nGenerated by \`npm run quality\` (ESLint, rules in \`eslint.config.js\` → \`QUALITY\`). Warnings only — nothing is blocked yet.\n\n`;
out += `| Standard | Limit | Breaches |\n|---|---|---|\n`;
for (const r of RULES) out += `| \`${r}\` | ${limit(r)} | ${by(r).length} |\n`;
for (const r of RULES) {
  const list = by(r);
  if (!list.length) continue;
  out += `\n## ${r} (limit ${limit(r)})\n\n| Value | Where | Function |\n|---|---|---|\n`;
  for (const x of list)
    out += `| ${x.value ?? "—"} | \`${x.file}:${x.line}\` | ${x.name || "—"} |\n`;
}
const perFile = {};
for (const x of rows) perFile[x.file] = (perFile[x.file] || 0) + 1;
out += `\n## Breaches per file\n\n| File | Breaches |\n|---|---|\n`;
for (const [f, n] of Object.entries(perFile).sort((a, b) => b[1] - a[1]))
  out += `| \`${f}\` | ${n} |\n`;
out += await cleanCodeSection();
console.log(out);

// ── Clean Code targets (Fix 26): breaches per file against the stricter targets ──
async function cleanCodeSection() {
  const rule = (max) => ["warn", { max, skipBlankLines: true, skipComments: true, IIFEs: true }];
  const warn = Object.fromEntries(Object.entries(TARGETS).map(([k, v]) => [k, ["warn", v[1]]]));
  const lint = (files, max) =>
    new ESLint({
      overrideConfig: { rules: { ...warn, "max-lines-per-function": rule(max) } },
    }).lintFiles(files);
  const results = [
    ...(await lint(["src/**/*.js", "api/**/*.js"], TARGET_LENGTH.logic)),
    ...(await lint(["src/**/*.jsx"], TARGET_LENGTH.component)),
  ];
  const ruleIds = [...Object.keys(TARGETS), "max-lines-per-function"];
  const rows = results
    .map((f) => ({
      file: f.filePath
        .replace(/\\/g, "/")
        .split("/")
        .slice(-3)
        .join("/")
        .replace(/^.*?(src|api)\//, "$1/"),
      n: f.messages.filter((m) => ruleIds.includes(m.ruleId)).length,
    }))
    .sort((a, b) => b.n - a.n || a.file.localeCompare(b.file));
  const clean = rows.filter((r) => r.n === 0);
  let s = `\n## Clean Code targets (Fix 26)\n\nLogic ≤ ${TARGET_LENGTH.logic} lines, components ≤ ${TARGET_LENGTH.component}, nesting ≤ 2, complexity ≤ 10, ≤ 3 params, files ≤ 300.\n\n`;
  s += `**${clean.length} of ${rows.length} files meet every target** (${CLEAN_FILES.length} locked in as lint errors). ${rows.reduce((t, r) => t + r.n, 0)} breaches in total.\n\n| File | Breaches |\n|---|---|\n`;
  for (const r of rows.filter((r) => r.n)) s += `| \`${r.file}\` | ${r.n} |\n`;
  return s;
}
